### PR TITLE
new feature: DNS Server - allows for captive portals

### PR DESCRIPTION
**Pull request by patrickjahns**
See NONOS https://github.com/SmingHub/Sming/pull/633

### CODE REVIEW

**Comment by alonewolfx2** [comment]
it has an error. please check it.

**Comment by patrickjahns** [comment]
@alonewolfx2 
Initially it was related to different naming conventions (Wstring/Wstring.h vs wstring/wstring.h) - I don`t have a local rtos sdk to test with currently. The error is now in the example and I am quite unsure what has changed between sming rtos and nonos in that sense

**Comment by alonewolfx2** [comment]
ok please change this line https://github.com/SmingHub/SmingRTOS/pull/83/files#diff-8187b1c4bfe50df858c9466c296a4c22R17
to
#include "../wiring/WString.h"
and try again. propably it will success

**Comment by patrickjahns** [comment]
Already did - the example application is still failing. 

How did you test your example? What is different in using RTOS vs NONOS Sming in that sense?

**Comment by alonewolfx2** [comment]
close & open for re-test travis

**Comment by alonewolfx2** [comment]
i am on windows. both  compiling fine for me

**Comment by patrickjahns** [comment]
Travis log shows these errors

```
make[1]: Entering directory `/home/travis/build/SmingHub/SmingRTOS/samples/DNSCaptivePortal'
C+ app/application.cpp
app/application.cpp:4:1: error: 'DNSServer' does not name a type
 DNSServer dnsServer;
 ^
app/application.cpp: In function 'void startServers()':
app/application.cpp:28:2: error: 'dnsServer' was not declared in this scope
  dnsServer.start(DNS_PORT, "*", apIP);
  ^
app/application.cpp: In function 'void init()':
app/application.cpp:43:9: error: 'class SystemClass' has no member named 'onReady'
  System.onReady(startServers);
         ^
make[1]: *** [out/build/app/application.o] Error 1
make[1]: Leaving directory `/home/travis/build/SmingHub/SmingRTOS/samples/DNSCaptivePortal'
make: *** [DNSCaptivePortal] Error 2
```

Is System.onReady deprecated?

**Comment by alonewolfx2** [comment]
@hreintke can you help us?

**Comment by hreintke** [comment]
@patrickjahns  @alonewolfx2 : 

Yes, onReady is not available in RTOS. It is not implemented in the Espressif SDK.
Applications can now use the new WifiEvents class to know the status.
Sorry, I thought I had documented that in the Readme but it isn't.

On application error : Did you include DNSServer.h in SmingCore ?

**Comment by patrickjahns** [comment]
@hreintke 
I got confused with `sming/sming/include/SmingIncludes.h` and  `sming/include/SmingCore.h`

Now it is working - already set onReceive to virtual and added callback

**Comment by hreintke** [comment]
In RTOS I separated the include fro framework build (SmingIncludes) from application build (SmingCore).
Just in order not to get  unnecessary includes.

**Pull request merged**
